# Generated by Django 3.1.2 on 2020-11-21 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('result_received', models.DateTimeField()),
                ('result', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('isMole', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('isTrue', models.BooleanField(default=True)),
                ('evidence_type', models.CharField(choices=[('W', 'Weapon'), ('L', 'Location'), ('P', 'Person'), ('S', 'Statement')], default='W', max_length=2)),
                ('finder', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='finder', to='mole.user')),
                ('sharedWith', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mole.user')),
            ],
        ),
    ]
