# Generated by Django 3.1.2 on 2020-12-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('occasion_type', models.CharField(choices=[('M', 'Minigame'), ('O', 'Occasion')], default='O', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('evidence_type', models.CharField(choices=[('CS', 'Tatort'), ('ME', 'Fluchtmittel'), ('O', 'Täter'), ('TC', 'Tatzeit'), ('W', 'Waffen')], default='W', max_length=2)),
                ('evidence_subtype', models.CharField(choices=[('CC', 'Merkmal'), ('CG', 'Kleidung'), ('CR', 'Farbe'), ('CN', 'Zustand'), ('DE', 'Tageszeit'), ('DT', 'Stadtviertel'), ('ER', 'Fluchtweg'), ('L', 'Ort'), ('M', 'Modell'), ('O', 'Gegenstand'), ('S', 'Größe'), ('TE', 'Temperatur'), ('TI', 'Uhrzeit'), ('W', 'Wochentag')], default='O', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='MimePair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_generic_term', models.CharField(max_length=50)),
                ('terms_to_be_mimed', models.CharField(max_length=200)),
                ('fake_generic_terms', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WouldYouRatherPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=200)),
                ('b', models.CharField(max_length=200)),
            ],
        ),
    ]
