# Generated by Django 3.1.2 on 2020-11-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mole', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evidence',
        ),
        migrations.AlterField(
            model_name='event',
            name='initiated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
