# Generated by Django 3.1.2 on 2021-01-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mole', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='subtype',
            field=models.CharField(choices=[('CC', 'Merkmal'), ('CG', 'Kleidung'), ('CR', 'Farbe'), ('CLR', 'Farbe'), ('CN', 'Zustand'), ('DE', 'Tageszeit'), ('DT', 'Stadtviertel'), ('ER', 'Fluchtweg'), ('L', 'Ort'), ('M', 'Modell'), ('O', 'Gegenstand'), ('S', 'Größe'), ('TE', 'Temperatur'), ('TI', 'Uhrzeit'), ('W', 'Wochentag')], default='O', max_length=3),
        ),
    ]
