# Generated by Django 3.1.2 on 2020-12-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mole', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfield',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='wouldyouratherpair',
            name='a',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='wouldyouratherpair',
            name='b',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
