# Generated by Django 3.1.2 on 2020-11-11 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mole', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='evidence_type',
            field=models.CharField(choices=[('W', 'Weapon'), ('L', 'Location'), ('P', 'Person'), ('S', 'Statement')], default=('P', 'Person'), max_length=2),
        ),
        migrations.AddField(
            model_name='evidence',
            name='finder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='finder', to='mole.user'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='sharedWith',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mole.user'),
        ),
        migrations.AlterField(
            model_name='event',
            name='initiated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
