# Generated by Django 3.1.2 on 2020-12-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mole', '0002_auto_20201204_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfield',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
