# Generated by Django 3.1.2 on 2020-11-11 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mole', '0002_auto_20201111_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('isTrue', models.BooleanField(default=True)),
                ('evidence_type', models.CharField(choices=[('W', 'Weapon'), ('L', 'Location'), ('P', 'Person'), ('S', 'Statement')], default=('P', 'Person'), max_length=2)),
                ('finder', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='finder', to='mole.user')),
                ('sharedWith', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mole.user')),
            ],
        ),
    ]
