# Generated by Django 3.1.2 on 2020-11-11 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mole', '0003_evidence'),
        ('mole', '0002_auto_20201111_1836'),
    ]

    operations = [
    ]
