# Generated by Django 3.1.2 on 2021-01-02 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mole', '0003_auto_20201208_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evidence',
            old_name='evidence_subtype',
            new_name='subtype',
        ),
        migrations.RenameField(
            model_name='evidence',
            old_name='evidence_type',
            new_name='type',
        ),
    ]
